### ISSUE TITLE
Hot reload not working in newest commit

### ISSUE THREAD

**Issue by ziontee113** [L3MON4D3/LuaSnip#862] opened 2023-04-11 02:07 UTC
Hi @L3MON4D3 , I updated my plugins recently and today I noticed that the hot reload feature doesn't work anymore. After some panicking, I locked my LuaSnip to commit d404ec306bfa4cdb0c3605dbb17e8a93a9597337, and it works just fine.

I just randomly picked a significant older commit to try out. I haven't tried other commits due to lack of time.

Please tell me if there's any more helpful information I can provide. Thank you very much.

**Comment by L3MON4D3** [comment] 2023-04-11 06:46
Okay pretty sure this is an issue with neovim, for me everything works correctly after `vim.loader.disable()` (or changing more than one letter in the file, such that its length changes) (seems like the issue is [here](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/loader.lua#L220-L226) somewhere)
The reason for an older commit of luasnip also working out should be that `loadfile` is cached by neovim, while what we did previously, reading and generating bytecode via `loadstring`, was not.

I'll throw together a MWE later, but technically, I'm a bit surprised the `vim.loader`-code is (presumably :sweat_smile:) messing up there, it all looks correct :shrug:

**Comment by L3MON4D3** [comment] 2023-04-11 08:33
NVM, I think it's with lazy, opened an [issue](https://github.com/folke/lazy.nvim/issues/720) about it

**Comment by L3MON4D3** [comment] 2023-04-11 10:46
Thought so too, but something is interfering if lazy is used :/
(check the bug-report, `-u NONE` works)

**Comment by leiserfg** [comment] 2023-04-11 10:59
Because it is opt-in and by using lazy you are opting in already.

**Comment by L3MON4D3** [comment] 2023-04-11 11:04
I'll update the PRs in a bit

**Comment by L3MON4D3** [comment] 2023-04-11 11:16
> I think you can do `vim.loader.reset(path)` if `vim.loader` is available.

Right, that would be a temporary fix.. tbh, might as well add that for now, fixing the bug might take longer

**Comment by L3MON4D3** [comment] 2023-04-15 15:28
Okay this is now fixed in neovim, but since v0.9 contains the bug (I think), I'll leave the temporary fix from 632d3d5 active since it shouldn't make a big difference

**Closed by L3MON4D3** 2023-04-15 15:28 UTC
