### ISSUE TITLE
worry number of arguments to 'insert' (Path.normalize failed on Windows)

### ISSUE THREAD

**Issue by Verf** [L3MON4D3/LuaSnip#548] opened 2022-08-22 01:55 UTC
Error Message: `Error running config for LuaSnip: ..packer\start\LuaSnip\lua\luasnip\loaders\from_vscode.lua:142: wrong number of arguments to 'insert'`

I found the last commit 2368d62 use Path.normalize to normlize path, but this function failed on Windows system:
```lua
Path.normalize(Path.join(root, snippet_entry.path))
-- root -> C:\Users\fht\AppData\Local\nvim\vsnip
-- snippet_entry.path -> ./global.json
-- Path.join(root, snippet_entry.path) -> C:\Users\fht\AppData\Local\nvim\vsnip\./global.json
-- Path.normalize(Path.join(root, snippet_entry.path)) -> nil
```

A quick and dirty fix is :
```lua
local filename = string.gsub(snippet_entry.path, "^%.[%/%\\]", "")
table.insert(
    ft_files[ft],
    Path.normalize(Path.join(root, filename)) 
) 
```

**Comment by c3n21** [comment] 2022-08-22 06:54
I'm getting the same error on Linux

```
Error in packer_compiled: ...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:142: wrong number of arguments to 'insert'
```

if I hard reset to this hash

```
fc25e77d74efb06033355b2175e2f5b78d15e7df
```

the error disappears

**Comment by leiserfg** [comment] 2022-08-22 07:24
@c3n21 can you share how are you using the loader? To try to reproduce the error.

**Comment by leiserfg** [comment] 2022-08-22 07:28
@Verf can you check if this (no so dirty fix)  works in windows? 
function Path.join(...)
	return vim.fs.normalize(table.concat({ ... }, sep))
end

**Comment by Verf** [comment] 2022-08-22 08:33
> @Verf can you check if this (no so dirty fix) works in windows?
> 
> ```lua
> function Path.join(...)
> 	return vim.fs.normalize(table.concat({ ... }, [[/]]))
> end
> ```

It can only be worked on the nightly build, but can not work on the latest stable build (nvim v0.7.2), because vim.fs does't exist.

**Comment by leiserfg** [comment] 2022-08-22 08:36
Well, but if it works then we could vendorize it.

**Comment by Verf** [comment] 2022-08-22 09:07
That's it.

**Comment by c3n21** [comment] 2022-08-22 09:17
> @c3n21 can you share how are you using the loader? To try to reproduce the error.

```lua
local luasnip = require('luasnip')
local types = require('luasnip.util.types')

luasnip.config.set_config({
    history = true,
    updateevents = 'TextChanged,TextChangedI',
    enable_autosnippets = true,
    ext_opts = {
        [types.choiceNode] = {
            active = {
                virt_text = {
                    {
                        '<-',
                        'Error',
                    },
                },
            },
        },
    },
})

local luasnip_snippets_realpath = string.format('%s/lua/config/plugins/LuaSnip/snippets', vim.fn.stdpath('config'))
local vscode_snippets_realpath =
    string.format('%s/lua/config/plugins/LuaSnip/friendly-snippets', vim.fn.stdpath('config'))
require('luasnip.loaders.from_lua').load({ paths = luasnip_snippets_realpath })
require('luasnip.loaders.from_vscode').lazy_load({ paths = { vscode_snippets_realpath } })
```

this is the code I use to run LuaSnip. If I comment the last line it works but obviously it doesn't load vscode's snippets.

Obviously I have my snippets in **vscode_snippets_realpath**

**Comment by L3MON4D3** [comment] 2022-08-22 09:44
TBH I'm a bit surprised that luv's `fs_realpath` (which we use for normalizing the path) fails at `C:\Users\fht\AppData\Local\nvim\vsnip\./global.json`. Is `./` not used on windows?
@Verf could you post the result for a few combinations, like only `\` or `/` for path separators, no `./` (with `:lua =vim.loop.fs_realpath(path)`)?

**Comment by L3MON4D3** [comment] 2022-08-22 09:46
> > @c3n21 can you share how are you using the loader? To try to reproduce the error.
> 
> ```lua
> local luasnip = require('luasnip')
> local types = require('luasnip.util.types')
> 
> luasnip.config.set_config({
>     history = true,
>     updateevents = 'TextChanged,TextChangedI',
>     enable_autosnippets = true,
>     ext_opts = {
>         [types.choiceNode] = {
>             active = {
>                 virt_text = {
>                     {
>                         '<-',
>                         'Error',
>                     },
>                 },
>             },
>         },
>     },
> })
> 
> local luasnip_snippets_realpath = string.format('%s/lua/config/plugins/LuaSnip/snippets', vim.fn.stdpath('config'))
> local vscode_snippets_realpath =
>     string.format('%s/lua/config/plugins/LuaSnip/friendly-snippets', vim.fn.stdpath('config'))
> require('luasnip.loaders.from_lua').load({ paths = luasnip_snippets_realpath })
> require('luasnip.loaders.from_vscode').lazy_load({ paths = { vscode_snippets_realpath } })
> ```
> 
> this is the code I use to run LuaSnip. If I comment the last line it works but obviously it doesn't load vscode's snippets.
> 
> Obviously I have my snippets in **vscode_snippets_realpath**

Could you make sure all files listed in `package.json` actually exist? Previously that didn't matter, but now it does since `Path.normalize` returns nil on a non-existent file, leading to an error

**Comment by c3n21** [comment] 2022-08-22 10:11
> > > @c3n21 can you share how are you using the loader? To try to reproduce the error.
> > 
> > 
> > ```lua
> > local luasnip = require('luasnip')
> > local types = require('luasnip.util.types')
> > 
> > luasnip.config.set_config({
> >     history = true,
> >     updateevents = 'TextChanged,TextChangedI',
> >     enable_autosnippets = true,
> >     ext_opts = {
> >         [types.choiceNode] = {
> >             active = {
> >                 virt_text = {
> >                     {
> >                         '<-',
> >                         'Error',
> >                     },
> >                 },
> >             },
> >         },
> >     },
> > })
> > 
> > local luasnip_snippets_realpath = string.format('%s/lua/config/plugins/LuaSnip/snippets', vim.fn.stdpath('config'))
> > local vscode_snippets_realpath =
> >     string.format('%s/lua/config/plugins/LuaSnip/friendly-snippets', vim.fn.stdpath('config'))
> > require('luasnip.loaders.from_lua').load({ paths = luasnip_snippets_realpath })
> > require('luasnip.loaders.from_vscode').lazy_load({ paths = { vscode_snippets_realpath } })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this is the code I use to run LuaSnip. If I comment the last line it works but obviously it doesn't load vscode's snippets.
> > Obviously I have my snippets in **vscode_snippets_realpath**
> 
> Could you make sure all files listed in `package.json` actually exist? Previously that didn't matter, but now it does since `Path.normalize` returns nil on a non-existent file, leading to an error

![image](https://user-images.githubusercontent.com/37077738/185896460-79b093aa-9419-4bcd-89fb-572667da8daa.png)


Seems like this file was missing, now it works.

Thanks!

Could it be possible to have a more descriptive error in such cases? Something like "snippets defined in package.json's doesn't match with the actual snippets in <path>"

**Comment by leiserfg** [comment] 2022-08-22 10:16
> Could it be possible to have a more descriptive error in such cases? Something like "snippets defined in package.json's doesn't match with the actual snippets in "

Yes, we plan to add an optional panic/logging mechanism, but haven't  decided on the API yet (is not fun and we are lazy :smiley: )

**Comment by L3MON4D3** [comment] 2022-08-22 10:16
> Could it be possible to have a more descriptive error in such cases? Something like "snippets defined in package.json's doesn't match with the actual snippets in "

Yep yep, definitely. I'll have to get started on adding logging, this missing file is probably something we don't need to throw an error for (could be annoying for inexperienced users) but should mention in the log.

**Comment by L3MON4D3** [comment] 2022-08-22 10:17
> (is not fun and we are lazy :smile: )

:shushing_face::shushing_face: :P

**Comment by Verf** [comment] 2022-08-22 11:23
> TBH I'm a bit surprised that luv's `fs_realpath` (which we use for normalizing the path) fails at `C:\Users\fht\AppData\Local\nvim\vsnip\./global.json`. Is `./` not used on windows? @Verf could you post the result for a few combinations, like only `\` or `/` for path separators, no `./` (with `:lua =vim.loop.fs_realpath(path)`)?

I see, the point is that I was missing the global.json file (It can be used normally without this file in the previous version, but now it is essential.). If the file does not exist, fs_realpath will return nil. I touched an empty global.json, and fs_realpath can parse `C:\Users\fht\AppData\Local\nvim\vsnip\./global.json` to `C:\Users\fht\AppData\Local\nvim\vsnip\global.json` correctly.

**Comment by leiserfg** [comment] 2022-08-22 11:28
Then my pr is not required.

**Comment by Verf** [comment] 2022-08-22 11:28
This is an unexpected breaking change 🤪 .

**Comment by L3MON4D3** [comment] 2022-08-22 11:34
Ahhhhh haha, okay that's very nice, this leaves the code much cleaner.

> This is an unexpected breaking change :zany_face

Surprise Breaking Change aka Bug :P
I'll fix that code up so it silently fails, when logging is in place we'll do some more there.

**Comment by L3MON4D3** [comment] 2022-08-22 11:45
Okay, should be fixed now!

**Closed by L3MON4D3** 2022-08-22 11:45 UTC

**Comment by leiserfg** [comment] 2022-08-22 14:10
> I'll fix that code up so it silently fails, when logging is in place we'll do some more there.

I'm inclined to think this is not something we should just skip, but something we should  `assert` instead. Because it will bring another kind of error, the "nothing happens" one, and those are harder to debug.

**Comment by L3MON4D3** [comment] 2022-08-22 15:37
Yeah, that's a good point.

Do you think the missing json-file should always be an error, even if we have the option to just log it?

(Because right now I think it should be logged (once we have that option), turning it into an error now would mean removing that later on, which feels a bit weird (changing behaviour often))

I think I'd rather sit this out until we have logging, ignoring missing files has worked pretty well so far :sweat_smile: (unless ofc logging isn't the right way, but I haven't found a good reason for throwing an error yet)

**Comment by leiserfg** [comment] 2022-08-22 16:16
Maybe instead of logging we should have a `panic` toggle, off by default, that allows weird (known) things to happen and breaks (with the important info we have at hand) when enabled. Basically just `assert` inside of an `if`.

**Comment by leiserfg** [comment] 2022-08-22 16:17
And then we recommend setting it `on` if something rare is happening.

**Comment by L3MON4D3** [comment] 2022-08-22 17:07
Hmmm, interesting.

It's nice because it's more immediate, there is probably more context than with a log.
We could do this in addition to logging (if there is important info, it should be stored in the log), I wouldn't replace logging with that toggle since taking look at the log of the past session should be faster than recreating some error with the toggle set to on this time.
