### ISSUE TITLE
unexpected behaviour of choice_active()

### ISSUE THREAD

**Issue by f3fora** [L3MON4D3/LuaSnip#18] opened 2021-05-13 19:01 UTC
Sometimes it happens that `require('luasnip').choice_active()` returns `true` even if no snippet exists, for example after `LuaSnipUnlinkCurrent` execution or because `history = false`.

Moreover if no snippets exists, `LuaSnipUnlinkCurrent` raises an error: 'LuaSnip/lua/luasnip/init.lua:82: attempt to index a nil value'. I think having a `print('Hey! no more snippet here')` should be cooler.

**Comment by L3MON4D3** [comment] 2021-05-13 19:21
Good points, does the first one only occur after unlinking?
That would be by design (if I understand your issue correctly) as an unlinked snippet cannot be entered after leaving, but LuasnipUnlinkCurrent doesn't leave eg. a choiceNode by itself.
The second is a good idea, I'll add it soon.

**Comment by f3fora** [comment] 2021-05-13 19:32
> Good points, does the first one only occur after unlinking?
> That would be by design (if I understand your issue correctly) as an unlinked snippet cannot be entered after leaving, but LuasnipUnlinkCurrent doesn't leave eg. a choiceNode by itself.

Ok! I think this is what it's happening!

But, I think, this map needs to be changed `imap <silent><expr> <C-E> luasnip#choice_active() ? '<Plug>luasnip-next-choice' : '<C-E>'`, because the condition in `require("luasnip").choice_active()` raises an error `/LuaSnip/lua/luasnip/nodes/node.lua:77: attempt to perform arithmetic on a nil value` when called.

**Comment by L3MON4D3** [comment] 2021-05-13 19:42
I think/fear the mapping is correct :|.
Does it error every time or only in a specific situation?

**Comment by f3fora** [comment] 2021-05-13 20:01
To reproduce:
- Be in a choice entry
- Call `LuaSnipUnlinkCurrent`
- Type `<C-E>`

This happens because `require("luasnip").choice_active()` will return `true` because the last entry was a choice and so `<Plug>luasnip-next-choice` will be execute.

**Comment by L3MON4D3** [comment] 2021-05-14 07:06
Oh, you're right, I completely missed that, thanks!
Should be fixed now.

**Closed by L3MON4D3** 2021-05-14 07:06 UTC

**Comment by f3fora** [comment] 2021-05-14 07:58
Thanks!
